Finish Dispatch Mechanism; add error message

diff --git a/docm b/docm
--- a/docm
+++ b/docm
@@ -1,3 +1,11 @@
 #!/bin/sh
-echo "$1\n"
-./$(($1))
+cmd="$1"
+shift
+
+if [ -e docm-$cmd ]
+then
+    exec "./docm-$cmd" "$@"
+else
+    echo "docm: fatal: function \"$cmd\" not found" >&2
+fi
+
