Fix binary search; correct in-place sorting; add make-link

diff --git a/docm-set-attribute b/docm-set-attribute
--- a/docm-set-attribute
+++ b/docm-set-attribute
@@ -10,9 +10,11 @@ fi
 
 if [[ $2 == *"="* ]]
 then
-    echo "docm: fatal: invalid attribute name \"$2\""
+    echo "docm: fatal: invalid attribute name \"$2\"" >&2
     exit 1
 fi
 
 echo "$2=$3" >> .docm/docs/$1
-sort -o .docm/docs/$1 .docm/docs/$1
+
+tmpfile=$(mktemp .docm/docs/$1.XXXXXX) || exit 1
+sort .docm/docs/$1 > "$tmpfile" && mv "$tmpfile" .docm/docs/$1
