Add extra options for help files and support documentation files

diff --git a/docm b/docm
--- a/docm
+++ b/docm
@@ -6,8 +6,18 @@ cmd="$1"
 if [ "$cmd" = "" ]
 then
     echo "docm: fatal: no arguments given" >&2
+    echo "For support with Docm, try 'docm help'" >&2
     exit 1
 fi
+
+while getopts ":h" option; do
+    case "$option" in
+        (h) docm-help
+            exit 0;;
+        (?) echo "docm: fatal: invalid option" >&2
+            echo "use 'docm help' for an overview of Docm" >&2;;
+    esac
+done
 
 shift
 
diff --git a/docm-help b/docm-help
--- a/docm-help
+++ b/docm-help
@@ -1,11 +1,25 @@
 #!/bin/sh
-echo "Docm
 
-Usage:
-    docm make-context
-    docm make-document <title>
-    docm rm-document <title>
-    docm cat-document <title>
-    docm set-attribute <document> <name> <value>
-    docm rm-attribute <document> <name> [<value>]
-    docm make-link <from> <type> <to>"
+if [ "$#" -lt "1" ]
+then
+    cat docs/docm.txt
+    exit 0
+fi
+
+while getopts ":l" option; do
+    case "$option" in
+        (l) ls docs
+            exit 0;;
+        (?) echo "docm: fatal: invalid option" >&2
+            echo "use 'docm help' for an overview of Docm" >&2;;
+    esac
+done
+
+if [ -e "docs/$1.txt" ]
+then
+    cat "docs/$1.txt"
+else
+    echo "docm: fatal: cannot find specified help file" >&2
+    echo "For a list of available pages use 'docm help -l'" >&2
+    exit 1
+fi
